# Generated by Django 2.1.15 on 2022-03-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookInventorys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinventory',
            old_name='description',
            new_name='author',
        ),
        migrations.AddField(
            model_name='bookinventory',
            name='dateCreated',
            field=models.CharField(default='', max_length=200),
        ),
    ]
